name: SeedDream 3.0 Daily Search

on:
  schedule:
    # Run at midnight UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  search:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      
      - name: Create search results directory
        run: mkdir -p search_results
      
      - name: Run SeedDream search
        id: search
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python scripts/search_seeddream.py
          echo "SEARCH_DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV
      
      - name: Commit and push results
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          
          # Add all new files in search_results directory
          git add search_results/
          
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "SeedDream search results for ${{ env.SEARCH_DATE }}"
            git push
          fi
      
      - name: Create issue if new findings
        if: success()
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Get the latest search results file
            const fs = require('fs');
            const path = require('path');
            
            const resultsDir = path.join(process.env.GITHUB_WORKSPACE, 'search_results');
            const files = fs.readdirSync(resultsDir)
              .filter(file => file.endsWith('.md'))
              .sort()
              .reverse();
            
            if (files.length === 0) {
              console.log('No search result files found');
              return;
            }
            
            const latestFile = path.join(resultsDir, files[0]);
            const content = fs.readFileSync(latestFile, 'utf8');
            
            // Check if there are any findings
            const hasGithubResults = content.includes('## GitHub Results') && !content.includes('No GitHub results found');
            const hasArxivResults = content.includes('## arXiv Papers') && !content.includes('No arXiv papers found');
            const hasHuggingFaceResults = content.includes('## Hugging Face Models') && !content.includes('No Hugging Face models found');
            
            if (hasGithubResults || hasArxivResults || hasHuggingFaceResults) {
              // Create an issue with the findings
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: `SeedDream 3.0 Search Results - ${new Date().toISOString().split('T')[0]}`,
                body: `New findings in the daily search for SeedDream 3.0!\n\nSee the full report here: [${files[0]}](https://github.com/${context.repo.owner}/${context.repo.repo}/blob/main/search_results/${files[0]})\n\n${content}`
              });
            } else {
              console.log('No significant findings to report');
            }
